name: digraph-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: build tests
      run: make digraph-tests
    - name: test
      shell: bash
      run: |
        for DEG in 16 24 32
        do
            echo ""
            echo "degree ${DEG}"
            echo ""
            ./digraph-tests -n${DEG} -egfux -d20 -t10000
            ./digraph-tests -n${DEG} -s -d10 -t100
        done
